/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Song = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'link' : IDL.Text,
  'submittedBy' : IDL.Principal,
  'description' : IDL.Text,
  'likes' : IDL.Nat,
  'genre' : IDL.Text,
  'timestamp' : Time,
  'artist' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteSong' : IDL.Func([IDL.Nat], [], []),
  'getAllSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGenres' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getSong' : IDL.Func([IDL.Nat], [Song], ['query']),
  'getSongsByGenre' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
  'getTopSongs' : IDL.Func([IDL.Nat], [IDL.Vec(Song)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeSong' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitSong' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Song = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'link' : IDL.Text,
    'submittedBy' : IDL.Principal,
    'description' : IDL.Text,
    'likes' : IDL.Nat,
    'genre' : IDL.Text,
    'timestamp' : Time,
    'artist' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteSong' : IDL.Func([IDL.Nat], [], []),
    'getAllSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGenres' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getSong' : IDL.Func([IDL.Nat], [Song], ['query']),
    'getSongsByGenre' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
    'getTopSongs' : IDL.Func([IDL.Nat], [IDL.Vec(Song)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeSong' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitSong' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };